version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ${DEVCONTAINER_DOCKERFILE:-Dockerfile}
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - FLASK_CONFIG=dev
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/flask_db
    depends_on:
      - db
    # 明示的にコマンドを指定
    command: poetry run flask run --host=0.0.0.0 --port=5000

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=flask_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d 
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
