version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_CONFIG=dev
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/flask_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=flask_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  migration:
    build: .
    command: poetry run flask db upgrade
    environment:
      - FLASK_APP=app
      - FLASK_CONFIG=dev
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/flask_db
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  mysql_data:
