version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - ..:/app
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - FLASK_CONFIG=dev
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/flask_db
    depends_on:
      - db
    # 開発環境用のコマンド
    command: sleep infinity

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=flask_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
